service: housing-search-listener
provider:
  name: aws
  runtime: dotnet6
  memorySize: 2048
  tracing:
    lambda: true
    apiGateway: true
  vpc: ${self:custom.vpc.${opt:stage}}
  stage: ${opt:stage}
  region: eu-west-2

package:
  artifact: ./bin/release/net6.0/housing-search-listener.zip

functions:
  HousingSearchListener:
    name: ${self:service}-${self:provider.stage}
    handler: HousingSearchListener::HousingSearchListener.HousingSearchListener::FunctionHandler
    role: lambdaExecutionRole
    environment:            
      ELASTICSEARCH_DOMAIN_URL: ${ssm:/housing-search-api/${self:provider.stage}/elasticsearch-domain}
      PersonApiUrl: ${ssm:/housing-tl/${self:provider.stage}/person-api-url}
      PersonApiToken: ${ssm:/housing-tl/${self:provider.stage}/person-api-token}
      TenureApiUrl: ${ssm:/housing-tl/${self:provider.stage}/tenure-api-url}
      TenureApiToken: ${ssm:/housing-tl/${self:provider.stage}/tenure-api-token}
      AccountApiUrl: ${ssm:/housing-finance/${self:provider.stage}/account-api-url}
      AccountApiToken: ${ssm:/housing-tl/${self:provider.stage}/account-api-token}
      FinancialTransactionApiUrl: ${ssm:/housing-finance/${self:provider.stage}/financial-transaction-api-url}
      FinancialTransactionApiToken: ${ssm:/housing-finance/${self:provider.stage}/financial-transaction-api-token}
      AssetApiUrl: ${ssm:/housing-tl/${self:provider.stage}/asset-information-url}
      AssetApiToken: ${ssm:/housing-tl/${self:provider.stage}/asset-information-token}
      ProcessesApiUrl: ${ssm:/housing-tl/${self:provider.stage}/process-api-url-v1}
      ProcessesApiToken: ${ssm:/housing-tl/${self:provider.stage}/processes-api-token}
      ContractApiUrl: ${ssm:/housing-tl/${self:provider.stage}/contract-api-url}
      ContractApiToken: ${ssm:/housing-tl/${self:provider.stage}/contract-api-token} 
    events:
      - sqs: ${ssm:/sqs-queue/${self:provider.stage}/housing_search_listener_queue/arn}
resources:
  Resources:
    LambdaSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupName: ${self:service}-${self:provider.stage}-sg
        GroupDescription: Allow all outbound traffic
        SecurityGroupEgress:
          - IpProtocol: -1
            CidrIp: 0.0.0.0/0
        VpcId: ${self:custom.vpcId.${opt:stage}}
    lambdaExecutionRole:
      Type: AWS::IAM::Role
      Properties:
        Path: /${self:service}/${self:provider.stage}/
        RoleName: ${self:service}-lambdaExecutionRole
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
          - arn:aws:iam::aws:policy/AWSXRayDaemonWriteAccess
        Policies:          
          - PolicyName: manageLogs
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource:
                    - 'Fn::Join':
                        - ':'
                        - - 'arn:aws:logs'
                          - Ref: 'AWS::Region'
                          - Ref: 'AWS::AccountId'
                          - 'log-group:/aws/lambda/*:*:*'
                - Effect: "Allow"
                  Action:
                    - "s3:PutObject"
                    - "s3:GetObject"
                  Resource:
                    Fn::Join:
                      - ""
                      - - "arn:aws:s3:::"
                        - "Ref": "ServerlessDeploymentBucket"
          - PolicyName: lambdaInvocation
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - "lambda:InvokeFunction"
                  Resource: "*"          
          - PolicyName: sqsAccess
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - "sqs:ChangeMessageVisibility"
                    - "sqs:DeleteMessage"
                    - "sqs:GetQueueAttributes"
                    - "sqs:GetQueueUrl"
                    - "sqs:ListQueueTags"
                    - "sqs:ReceiveMessage"
                    - "sqs:SendMessage"
                    - "kms:Decrypt"
                  Resource: "*" 
custom:
  vpcId:
    development: vpc-0d15f152935c8716f
    staging: vpc-064521a7a4109ba31
    production: vpc-0ce853ddb64e8fb3c
  vpc:
    development:
      securityGroupIds:
        - Ref: LambdaSecurityGroup
      subnetIds:
        - subnet-0140d06fb84fdb547
        - subnet-05ce390ba88c42bfd
    staging:
      securityGroupIds:
        - Ref: LambdaSecurityGroup
      subnetIds:
        - subnet-0743d86e9b362fa38
        - subnet-0ea0020a44b98a2ca
    production:
      securityGroupIds:
        - Ref: LambdaSecurityGroup
      subnetIds:
        - subnet-06a697d86a9b6ed01
        - subnet-0beb266003a56ca82
